<?php

declare(strict_types=1);

use App\Http\Controllers\UserController;
use App\Models\Role;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Schema;
use Inertia\Inertia;
use Modules\Admin\Http\Controllers\ApplicationWorkflowController;
use Modules\Admin\Http\Controllers\EmailTemplateController;
use Modules\Admin\Http\Controllers\InstitutionController;
use Modules\Admin\Http\Controllers\InvoiceController;
use Modules\Admin\Http\Controllers\StaffController;
use Modules\Web\Http\Controllers\WebPortalController;

// Generated by PortalWiringService (migration:wire). Entry point routes each
// audience to its portal; real BC gov SSO is stubbed for now.

Route::get('/', fn () => redirect('/login'));
Route::get('/login', [UserController::class, 'login'])->name('login');
Route::post('/pdex-login', [UserController::class, 'pdexLogin'])->name('login.pdex');
Route::match(['get', 'post'], '/login/idir', [UserController::class, 'loginAsMinistry'])->name('login.idir');
Route::match(['get', 'post'], '/login/bceid', [UserController::class, 'loginAsInstitution'])->name('login.bceid');
Route::match(['get', 'post'], '/logout', [UserController::class, 'logout'])->name('logout');

// Institution (BCeID) web portal.
Route::prefix('web')->middleware('is.active:institution')->group(function () {
    $pages = json_decode('["AboutPage","AccountPage","AdvancedSearchPartialPage","AlertCampusPage","AlertsPage","ApplicationsPartialPage","BasePage","CreatePartialPage","DeletePartialPage","DisabledPage","EditEqaApplicationPage","EditPartialPage","HomePage","InstitutionPartialPage","InvoicePartialPage","MaintenancePage","NewApplicationPage","NotAuthorizedPage","ReportPage","VerifySealPage","VerifySealVerifyLogoPage","ViewStartPage"]', true) ?: [];

    Route::get('/', [WebPortalController::class, 'home'])->name('web.home');
    Route::get('/applications', [WebPortalController::class, 'applications'])->name('web.applications');
    Route::get('/applications/new', [WebPortalController::class, 'create'])->name('web.applications.new');
    Route::post('/applications', [WebPortalController::class, 'store'])->name('web.applications.store');
    Route::get('/applications/{crmId}', [WebPortalController::class, 'show'])->name('web.application.show');

    Route::get('/institution', [WebPortalController::class, 'institutionProfile'])->name('web.institution');
    Route::get('/institution/edit', [WebPortalController::class, 'editInstitution'])->name('web.institution.edit');
    Route::put('/institution', [WebPortalController::class, 'updateInstitution'])->name('web.institution.update');
    Route::get('/campuses', [WebPortalController::class, 'campuses'])->name('web.campuses');
    Route::get('/campuses/new', [WebPortalController::class, 'createCampus'])->name('web.campuses.new');
    Route::post('/campuses', [WebPortalController::class, 'storeCampus'])->name('web.campuses.store');
    Route::get('/campuses/{crmId}/edit', [WebPortalController::class, 'editCampus'])->name('web.campuses.edit');
    Route::put('/campuses/{crmId}', [WebPortalController::class, 'updateCampus'])->name('web.campuses.update');
    Route::patch('/campuses/{crmId}/toggle', [WebPortalController::class, 'toggleCampus'])->name('web.campuses.toggle');
    Route::delete('/campuses/{crmId}', [WebPortalController::class, 'destroyCampus'])->name('web.campuses.destroy');
    Route::get('/dbas', [WebPortalController::class, 'dbas'])->name('web.dbas');
    Route::get('/dbas/new', [WebPortalController::class, 'createDba'])->name('web.dbas.new');
    Route::post('/dbas', [WebPortalController::class, 'storeDba'])->name('web.dbas.store');
    Route::get('/dbas/{crmId}/edit', [WebPortalController::class, 'editDba'])->name('web.dbas.edit');
    Route::put('/dbas/{crmId}', [WebPortalController::class, 'updateDba'])->name('web.dbas.update');
    Route::patch('/dbas/{crmId}/toggle', [WebPortalController::class, 'toggleDba'])->name('web.dbas.toggle');
    Route::delete('/dbas/{crmId}', [WebPortalController::class, 'destroyDba'])->name('web.dbas.destroy');
    Route::get('/users', [WebPortalController::class, 'users'])->name('web.users');
    Route::put('/users/{userId}/role', [WebPortalController::class, 'updateStaffRole'])->name('web.users.role');

    // Browse any captured Web page by name (raw migrated views).
    Route::get('/view/{page}', function (string $page) use ($pages) {
        abort_unless(in_array($page, $pages, true), 404);

        return Inertia::render('Web/RawPage', ['module' => 'Web', 'page' => $page]);
    })->name('web.view');

    // End a ministry impersonation session and return to the admin portal.
    Route::post('/stop-impersonating', [InstitutionController::class, 'stopImpersonating'])->name('web.impersonate.stop');
});

// Ministry (IDIR) admin portal (generated from Dynamics migration later).
Route::middleware('is.active:ministry')->group(function () {
    Route::get('/admin', fn () => Inertia::render('Admin/Dashboard'))->name('admin.home');

    // Ministry staff maintenance (roles + active status).
    Route::get('/admin/staff', [StaffController::class, 'index'])->name('admin.staff');
    Route::put('/admin/staff/{user}/role', [StaffController::class, 'updateRole'])->name('admin.staff.role');
    Route::put('/admin/staff/{user}/status', [StaffController::class, 'updateStatus'])->name('admin.staff.status');
Route::get('/admin/institutions', function () {
    $institutions = collect();
    if (Schema::hasTable('institutions')) {
        $query = DB::table('institutions as i')->orderBy('i.name')->select('i.*');
        if (Schema::hasTable('dbas')) {
            $query->selectSub(
                DB::table('dbas')->selectRaw('COUNT(*)')->whereColumn('dbas.institution_crm_id', 'i.crm_id'),
                'dba_count'
            );
        }
        $institutions = $query->get();
    }

    return Inertia::render('Admin/Institutions', ['institutions' => $institutions]);
})->name('admin.institutions');

// Admin institution view — manage its Locations (campuses) and Contacts (users).
Route::get('/admin/institutions/{crmId}', [InstitutionController::class, 'show'])->name('admin.institution.show');
Route::get('/admin/institutions/{crmId}/edit', [InstitutionController::class, 'edit'])->name('admin.institution.edit');
Route::put('/admin/institutions/{crmId}', [InstitutionController::class, 'update'])->name('admin.institution.update');
Route::put('/admin/institutions/{crmId}/designation', [InstitutionController::class, 'updateDesignation'])->name('admin.institution.designation.update');
Route::get('/admin/institutions/{crmId}/campuses/new', [InstitutionController::class, 'createCampus'])->name('admin.institution.campus.new');
Route::post('/admin/institutions/{crmId}/campuses', [InstitutionController::class, 'storeCampus'])->name('admin.institution.campus.store');
Route::get('/admin/institutions/{crmId}/campuses/{campusId}/edit', [InstitutionController::class, 'editCampus'])->name('admin.institution.campus.edit');
Route::put('/admin/institutions/{crmId}/campuses/{campusId}', [InstitutionController::class, 'updateCampus'])->name('admin.institution.campus.update');
Route::patch('/admin/institutions/{crmId}/campuses/{campusId}/toggle', [InstitutionController::class, 'toggleCampus'])->name('admin.institution.campus.toggle');
Route::delete('/admin/institutions/{crmId}/campuses/{campusId}', [InstitutionController::class, 'destroyCampus'])->name('admin.institution.campus.destroy');
Route::get('/admin/institutions/{crmId}/users/new', [InstitutionController::class, 'createUser'])->name('admin.institution.user.new');
Route::post('/admin/institutions/{crmId}/users', [InstitutionController::class, 'storeUser'])->name('admin.institution.user.store');
Route::get('/admin/institutions/{crmId}/users/{userId}/edit', [InstitutionController::class, 'editUser'])->name('admin.institution.user.edit');
Route::put('/admin/institutions/{crmId}/users/{userId}', [InstitutionController::class, 'updateUser'])->name('admin.institution.user.update');
Route::patch('/admin/institutions/{crmId}/users/{userId}/toggle', [InstitutionController::class, 'toggleUser'])->name('admin.institution.user.toggle');
Route::delete('/admin/institutions/{crmId}/users/{userId}', [InstitutionController::class, 'destroyUser'])->name('admin.institution.user.destroy');
Route::put('/admin/institutions/{crmId}/staff/{user}/role', [InstitutionController::class, 'updateStaffRole'])->name('admin.institution.staff.role');
Route::put('/admin/institutions/{crmId}/staff/{user}/status', [InstitutionController::class, 'updateStaffStatus'])->name('admin.institution.staff.status');
Route::post('/admin/institutions/{crmId}/staff/{userId}/fetch-bceid', [InstitutionController::class, 'fetchBceid'])->name('admin.institution.staff.fetch-bceid');
Route::post('/admin/institutions/{crmId}/staff/{userId}/login', [InstitutionController::class, 'loginAsStaff'])->name('admin.institution.staff.login');
Route::get('/admin/institutions/{crmId}/dbas/new', [InstitutionController::class, 'createDba'])->name('admin.institution.dba.new');
Route::post('/admin/institutions/{crmId}/dbas', [InstitutionController::class, 'storeDba'])->name('admin.institution.dba.store');
Route::get('/admin/institutions/{crmId}/dbas/{dbaId}/edit', [InstitutionController::class, 'editDba'])->name('admin.institution.dba.edit');
Route::put('/admin/institutions/{crmId}/dbas/{dbaId}', [InstitutionController::class, 'updateDba'])->name('admin.institution.dba.update');
Route::patch('/admin/institutions/{crmId}/dbas/{dbaId}/toggle', [InstitutionController::class, 'toggleDba'])->name('admin.institution.dba.toggle');
Route::delete('/admin/institutions/{crmId}/dbas/{dbaId}', [InstitutionController::class, 'destroyDba'])->name('admin.institution.dba.destroy');

// Ministry DBAs (Doing Business As) across all institutions.
Route::get('/admin/dbas', function () {
    $dbas = Schema::hasTable('dbas')
        ? DB::table('dbas')->orderBy('institution_name')->orderBy('name')->limit(2000)->get()
        : collect();

    return Inertia::render('Admin/Dbas', ['dbas' => $dbas]);
})->name('admin.dbas');

Route::get('/admin/applications', function () {
    $applications = collect();
    if (Schema::hasTable('applications')) {
        $query = DB::table('applications as a')->orderByDesc('a.application_date')->limit(1000)->select('a.*');
        if (Schema::hasTable('invoices')) {
            $query->selectSub(
                DB::table('invoices')->select('crm_id')->whereColumn('invoices.application_crm_id', 'a.crm_id')->limit(1),
                'invoice_crm_id'
            );
        }
        $applications = $query->get();
    }

    return Inertia::render('Admin/Applications', ['applications' => $applications]);
})->name('admin.applications');

Route::get('/admin/applications/{crmId}', function (string $crmId) {
    abort_unless(Schema::hasTable('applications'), 404);
    $application = DB::table('applications')->where('crm_id', $crmId)->first();
    abort_if($application === null, 404);
    $invoice = Schema::hasTable('invoices')
        ? DB::table('invoices')->where('application_crm_id', $crmId)->first()
        : null;

    // PTIRU Standing is only relevant when the institution's quality assurance is
    // met through the Private Training designation, so surface its QA Met Through
    // value to let the review screen hide the PTIRU standing check otherwise.
    $qaMetThrough = ($application->institution_crm_id && Schema::hasTable('institutions'))
        ? optional(DB::table('institutions')->where('crm_id', $application->institution_crm_id)->first())->qa_met_through
        : null;

    return Inertia::render('Admin/ApplicationReview', [
        'application' => $application,
        'invoice' => $invoice,
        'qaMetThrough' => $qaMetThrough,
    ]);
})->name('admin.application.review');

Route::post('/admin/applications/{crmId}/advance', [ApplicationWorkflowController::class, 'advance'])->name('admin.application.advance');
Route::put('/admin/applications/{crmId}', [ApplicationWorkflowController::class, 'update'])->name('admin.application.update');

// Ministry invoices / financial summaries (+ Word order-receipt generation).
Route::get('/admin/invoices', [InvoiceController::class, 'index'])->name('admin.invoices');
Route::get('/admin/invoices/{crmId}', [InvoiceController::class, 'show'])->name('admin.invoice.show');
Route::get('/admin/invoices/{crmId}/receipt', [InvoiceController::class, 'receipt'])->name('admin.invoice.receipt');

// Ministry email templates (migrated CRM notification emails) + global master
// switch for email sending (default OFF). Ministry Admins only.
Route::middleware('role:'.Role::MINISTRY_ADMIN.','.Role::SUPER_ADMIN)->group(function () {
    Route::get('/admin/email-templates', [EmailTemplateController::class, 'index'])->name('admin.email-templates');
    Route::patch('/admin/email-templates/toggle', [EmailTemplateController::class, 'toggle'])->name('admin.email-templates.toggle');
    Route::patch('/admin/email-templates/settings', [EmailTemplateController::class, 'settings'])->name('admin.email-templates.settings');
    Route::put('/admin/email-templates/{id}', [EmailTemplateController::class, 'update'])->name('admin.email-templates.update');
    Route::post('/admin/email-templates/{id}/test', [EmailTemplateController::class, 'sendTest'])->name('admin.email-templates.test');
});
});
